
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightNEGnonassocPOWADD DIV ENDL LPAREN MUL NUM POW RPAREN SUBline : expr ENDLline : error ENDLexpr : numberexpr : LPAREN expr RPARENexpr : SUB LPAREN expr RPAREN %prec NEGexpr : expr ADD exprexpr : expr SUB exprexpr : expr MUL exprexpr : expr POW numberexpr : expr DIV exprnumber : NUMnumber : SUB number %prec NEG'
    
_lr_action_items = {'error':([0,],[3,]),'LPAREN':([0,5,6,9,10,11,13,17,],[5,5,17,5,5,5,5,5,]),'SUB':([0,2,4,5,6,7,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,],[6,10,-3,6,16,-11,6,6,6,16,6,10,16,6,-12,-6,-7,-8,-9,-10,-4,10,-5,]),'NUM':([0,5,6,9,10,11,12,13,16,17,],[7,7,7,7,7,7,7,7,7,7,]),'$end':([1,8,14,],[0,-1,-2,]),'ENDL':([2,3,4,7,18,19,20,21,22,23,24,26,],[8,14,-3,-11,-12,-6,-7,-8,-9,-10,-4,-5,]),'ADD':([2,4,7,15,18,19,20,21,22,23,24,25,26,],[9,-3,-11,9,-12,-6,-7,-8,-9,-10,-4,9,-5,]),'MUL':([2,4,7,15,18,19,20,21,22,23,24,25,26,],[11,-3,-11,11,-12,11,11,-8,-9,-10,-4,11,-5,]),'POW':([2,4,7,15,18,19,20,21,22,23,24,25,26,],[12,-3,-11,12,-12,12,12,12,-9,12,-4,12,-5,]),'DIV':([2,4,7,15,18,19,20,21,22,23,24,25,26,],[13,-3,-11,13,-12,13,13,-8,-9,-10,-4,13,-5,]),'RPAREN':([4,7,15,18,19,20,21,22,23,24,25,26,],[-3,-11,24,-12,-6,-7,-8,-9,-10,-4,26,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expr':([0,5,9,10,11,13,17,],[2,15,19,20,21,23,25,]),'number':([0,5,6,9,10,11,12,13,16,17,],[4,4,18,4,4,4,22,4,18,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expr ENDL','line',2,'p_line_expr','yaccrules.py',15),
  ('line -> error ENDL','line',2,'p_line_error','yaccrules.py',23),
  ('expr -> number','expr',1,'p_expr_number','yaccrules.py',33),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','yaccrules.py',39),
  ('expr -> SUB LPAREN expr RPAREN','expr',4,'p_expr_neg','yaccrules.py',43),
  ('expr -> expr ADD expr','expr',3,'p_expr_add','yaccrules.py',49),
  ('expr -> expr SUB expr','expr',3,'p_expr_sub','yaccrules.py',55),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','yaccrules.py',61),
  ('expr -> expr POW number','expr',3,'p_expr_pow','yaccrules.py',67),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','yaccrules.py',73),
  ('number -> NUM','number',1,'p_number_pos','yaccrules.py',83),
  ('number -> SUB number','number',2,'p_number_neg','yaccrules.py',87),
]
